### ISSUE TITLE
url with trainling slash  /blog/100/    match  r.GET(`/blog/{id:\d+}`,

### ISSUE THREAD

**Issue by tablecell** [gookit/rux#60]
**System (please complete the following information):**

 - OS: `win64` 
 - GO Version: `1.16` 
 - Pkg Version: `1.3.2` 

**Describe the bug**

**To Reproduce**

```go
package main

import (
	"github.com/gookit/rux"
)
func main() {
	r := rux.New()
	
	r.GET(`/blog/{id:\d+}`, func(c *rux.Context) {
        c.Text(200, "view detail, id: " + c.Param("id"))
	})
	r.Listen(":8080")
}
```

**Expected behavior**
 404 
 /blog/100/    not match  r.GET(`/blog/{id:\d+}`)

**Screenshots**

**Additional context**

**Comment by inhere** [comment]
hi, if you want strict check last slash char('/'), please add option: 

```go
r := rux.New(rux.StrictLastSlash)

// ...
```

now, access the `/blog/100/` will get 404, `/blog/100` is ok.
