### ISSUE TITLE
支持embed文件

### ISSUE THREAD

**Issue by ismlsmile** [gookit/rux#90]
前端工程编译到static目录，里面包含html、js等，一般都需要把这些文件做embed，这样携带方便。我看目前所有的StaticXXX接口都不支持此类embed，这个能支持吗？

**Comment by inhere** [comment]
可以的。我找时间看下。

**Comment by inhere** [comment]
hi @ismlsmile 

embed 是go 1.16+ 内置的，不需要其他改动。

可以直接用的，示例：

https://github.com/gookit/rux/blob/c4a59d4af3778b10e430621e99923995b520a8e0/_examples/serve/main.go#L15-L18

https://github.com/gookit/rux/blob/c4a59d4af3778b10e430621e99923995b520a8e0/_examples/serve/main.go#L36-L39

启动后，访问：`/embed/static/some.html` 是可以的
